### ISSUE TITLE
userContent.css

### ISSUE THREAD

**Issue by akvadrako** [trwnh/thunderbird57-userchrome-dark#1]
I have a comment on this code:

```css
//TODO: debug this
*/
browser#messagepane html, browser#messagepane html body {
	background: #333 !important;
	color: white !important;	
}
```

If you want to customize the message pane, you need to use `chrome/userContent.css`, not `userChrome.css`.
